export const CLIENT_CONNECTTED = 'CLIENT_CONNECTTED'
export const CLIENT_DISCONNECTTED = 'CLIENT_DISCONNECTTED'
export const CLIENT_JOIN = 'CLIENT_JOIN'
export const CLIENT_LEFT = 'CLIENT_LEFT'
export const CLIENT_GROUP_MSG = 'CLIENT_GROUP_MSG'
export const CLIENT_REQ_CONTROL = 'CLIENT_REQ_CONTROL'
export const CLIENT_REQ_REL_CONTROL = 'CLIENT_REQ_REL_CONTROL'

export const CLIENT_ADM_FORCE_REL_GRP_CONTROL = 'CLIENT_ADM_FORCE_REL_GRP_CONTROL'


// Following const should be shared with client src code
export const GROUP_TYPE_CHATANY = 'GROUP_TYPE_CHATANY'
export const GROUP_TYPE_ONEBOSS = 'GROUP_TYPE_ONEBOSS'
export const DEVICE_IPAD = 'DEVICE_IPAD'
export const DEVICE_IPHONE = 'DEVICE_IPHONE'
export const DEVICE_BROWSER = 'DEVICE_BROWSER'

// For SIC3
export const CLIENT_APPINFO_UPDATE = 'CLIENT_APPINFO_UPDATE'
export const CLIENT_DEVICEINFO_UPDATE = 'CLIENT_DEVICEINFO_UPDATE'
export const CLIENT_COREINFO_UPDATE = 'CLIENT_COREINFO_UPDATE'
export const CLIENT_ADM_CMD_TO_GROUP_MSG = 'CLIENT_ADM_CMD_TO_GROUP_MSG'
export const CLIENT_ADM_CMD_TO_SOCKET_MSG = 'CLIENT_ADM_CMD_TO_SOCKET_MSG'
