
export const REMOTE_STATE_CHANGE = 'REMOTE_STATE_CHANGE'
export const GLOBAL_USER_SET_PREFERENCE = 'GLOBAL_USER_SET_PREFERENCE'

// GLOBAL ACTION
export const GLOBAL_ADM_CMD_GROUP_MSG = 'GLOBAL_ADM_CMD_GROUP_MSG'
export const GLOBAL_ADM_CMD_SOCKET_MSG = 'GLOBAL_ADM_CMD_SOCKET_MSG'