
// App Status
export const ST_STOPPED = 'ST_STOPPED'
export const ST_STARTING = 'ST_STARTING'
export const ST_RUNNING = 'ST_RUNNING'
export const ST_STOPPING = 'ST_STOPPING'

// App Event
export const EVTS = {
  APP_STATUS_CHANGED: 'APP_STATUS_CHANGED',
  APP_ACTIVEURL_CHANGED: 'APP_ACTIVEURL_CHANGED',
  APP_UPGRADE_FINISHED: 'APP_UPGRADE_FINISHED'
}